# DNA to RNA Conversion
# Language: Julia
# Version: 1.5
# Difficulty: 8 kyu

function dnatorna(dna::String)
  replace(dna, "T" => "U")
end


# Tests
using FactCheck

facts("Fixed tests") do
  @fact dnatorna("TTTT") --> "UUUU"
  @fact dnatorna("GCAT") --> "GCAU"
  @fact dnatorna("") --> ""
  @fact dnatorna("T") --> "U"
  @fact dnatorna("GACCGCCGCC") --> "GACCGCCGCC"
  @fact dnatorna("GATTCCACCGACTTCCCAAGTACCGGAAGCGCGACCAACTCGCACAGC") --> "GAUUCCACCGACUUCCCAAGUACCGGAAGCGCGACCAACUCGCACAGC"
  @fact dnatorna("CACGACATACGGAGCAGCGCACGGTTAGTACAGCTGTCGGTGAACTCCATGACA") --> "CACGACAUACGGAGCAGCGCACGGUUAGUACAGCUGUCGGUGAACUCCAUGACA"
  @fact dnatorna("CACGACATACGGAGCAGCGCACGGTTAGTACAGCTGTCGGTGAACTCCATGACA") --> "CACGACAUACGGAGCAGCGCACGGUUAGUACAGCUGUCGGUGAACUCCAUGACA"
  @fact dnatorna("AACCCTGTCCACCAGTAACGTAGGCCGACGGGAAAAATAAACGATCTGTCAATG") --> "AACCCUGUCCACCAGUAACGUAGGCCGACGGGAAAAAUAAACGAUCUGUCAAUG"
end